src/accounts/urls.py
from django.urls import path
from accounts.views import (
    error503, store_login_view, logout_view,
    signup_view, personalize, skip_to_free,
    billing, login_view, create_merchant,
    create_user, errorNoNet, store_signup_view,
)


app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('create/store/', create_user, name='create-user'),
    path('create/<slug>/continue/<country>/<currency>/', create_merchant, name='create-merchant'),
    path('signup/store/<slug>/personalize', personalize, name='personalize'),
    path('signup/store/<slug>/billing', billing, name='billing'),
    path('signup/store/<slug>/skip-to-trial', skip_to_free, name='free-trial'),
    path('login/', login_view, name='login'),
    
    path('logout/', logout_view, name='logout'),
    path('error/503/', error503, name='error_503'),
    path('error/signup/failed/', errorNoNet, name='error-noNet'),
    #           Storefront urls
    path('<slug>/signup/', store_signup_view, name='store-signup'),
    path('<slug>/login/', store_login_view, name='store-login'),
]

src/api/urls.py
from django.urls import path
from .views import (
    CreateNewStore, index, index_new, StoreBackendView,
    StoreFrontView, LoginView, logout_view, MerchantView,
    MerchantCreateView,
)

app_name = 'api'

urlpatterns = [
    # api docs
    path('', index, name="index"),
    path('new/', index_new, name="index-new"),
    
    
    # Auth
    path('auth/logout/', logout_view, name="logout"),
    path('auth/login/', LoginView.as_view(), name="login"),

    # [Enpoints] '/new/'
    path('new/store/', CreateNewStore.as_view(), name="new-store"),
    path('new/vendor/', MerchantCreateView.as_view(), name="new-vendor"),
    
    # Store Frontend View
    path('store/<store>/', StoreFrontView.as_view(), name='store-view'),
    
    # Backend Views
    path('<slug>/admin/', StoreBackendView.as_view(), name="store-admin"),
    path('<slug>/owner/<id>', MerchantView.as_view(), name="merchant-view"),
]

src/vendora/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', include('intro.urls', namespace='base')),
    path('api/', include('api.urls', namespace='api')),
    path('<slug>/admin/', include('vendor.urls', namespace='vendor')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/home.html
{% load static %}
{% comment %} {% load hosts %} {% endcomment %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/store/default/mdb/mdb.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/global/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/global/base.css'%}">
    <link rel="stylesheet" href="{% static 'css/global/scrollbar.css'%}">
    <title>Vendora</title>
</head>
<body>
    <nav class="navbar sticky-top bg-dark-blue text-white" id="nav">
        <div class="container">
            <h1 class="navbar-brand"> Vendora! </h1>
            <div class="btn-group">
            {% if not request.user.is_authenticated %}
            <a class="btn bg-primary" href="{% url 'accounts:signup' %}">
                Sign Up
            </a>
            <a class="btn bg-secondary" href="{% url 'accounts:login' %}">
                Login
            </a>
            {% else %}
                {% if store %}
                <a class="btn bg-primary white-text" href="{% url 'vendor:dashboard' store.slug %}">
                    {{store.name}} Admin
                </a>
                {% endif %}
            
            {% endif %}
                
            </div>
        </div>
    </nav>

    <section class=" bg-dark-blue bg-store text-white row" id="intro">
        {% comment %} <div id="img1" class="col col-lg-6">
            <img src="{% static 'img/jpg/online-store.jpg' %}" id="online-store" class="img img-fluid">
        </div> {% endcomment %}
        <div id="intro-content" class="col col-lg-6">
            <h4> Welcome To Your New Online Store! </h4>
            <p> {% lorem 1 b  %} </p>
        </div>
    </section>

    <main role="main" class="p-5">
        <section id="we" class="mt-5 mb-5">
            <h3> What We Offer </h3>
            <article>{% lorem 2 b %} </article>
        </section>

        <section id="about" class="">
            <div id="customize">
                <img src="{% static 'img/svg/base/customize.svg' %}" id="customize-image">
                <div id="customize-content">
                    <h3> A Responsive And Customizable Site </h3>
                    <p> {% lorem 1 b %} </p>
                </div>
            </div>

            <div id="analysis">
                <img src="{% static 'img/svg/base/analysis.svg' %}" id="analysis-image">
                <div id="analysis-content" class="mt-5">
                    <h3> Fully Packed, Functional Backend </h3>
                    <p> {% lorem 1 b %} </p>
                </div>
            </div>
        </section>
    </main>
   
    
</body>
</html>