src/accounts/urls.py
from django.urls import path
from accounts.views import (
    error503, store_login_view, logout_view,
    signup_view, personalize, skip_to_free,
    billing, login_view, create_merchant,
    create_user, errorNoNet, store_signup_view,
)


app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('create/store/', create_user, name='create-user'),
    path('create/<slug>/continue/<country>/<currency>/', create_merchant, name='create-merchant'),
    path('signup/store/<slug>/personalize', personalize, name='personalize'),
    path('signup/store/<slug>/billing', billing, name='billing'),
    path('signup/store/<slug>/skip-to-trial', skip_to_free, name='free-trial'),
    path('login/', login_view, name='login'),
    
    path('logout/', logout_view, name='logout'),
    path('error/503/', error503, name='error_503'),
    path('error/signup/failed/', errorNoNet, name='error-noNet'),
    #           Storefront urls
    path('<slug>/signup/', store_signup_view, name='store-signup'),
    path('<slug>/login/', store_login_view, name='store-login'),
]

src/api/urls.py
from django.urls import path
from .views import (
    CreateNewStore, index, index_new, StoreBackendView,
    StoreFrontView, LoginView, logout_view, MerchantView,
    MerchantCreateView,
)

app_name = 'api'

urlpatterns = [
    # api docs
    path('', index, name="index"),
    path('new/', index_new, name="index-new"),
    
    
    # Auth
    path('auth/logout/', logout_view, name="logout"),
    path('auth/login/', LoginView.as_view(), name="login"),

    # [Enpoints] '/new/'
    path('new/store/', CreateNewStore.as_view(), name="new-store"),
    path('new/vendor/', MerchantCreateView.as_view(), name="new-vendor"),
    
    # Store Frontend View
    path('store/<store>/', StoreFrontView.as_view(), name='store-view'),
    
    # Backend Views
    path('<slug>/admin/', StoreBackendView.as_view(), name="store-admin"),
    path('<slug>/owner/<id>', MerchantView.as_view(), name="merchant-view"),
]

src/store/urls.py
from django.urls import path
from store.views import (
    product_view, store_view, cart_view,
    checkout_view, add_to_cart, redeem_coupon,
    on_checkout_success, increase_cart_item,
    decrease_cart_item, change_cart_item, 
    search_view, add_to_wish, remove_wish,
    delete_cart_item, wish_view, checkout,
    closed_view,
)

# Url routing namespace dependency
app_name = 'store'

urlpatterns = [
    path('<slug>/', store_view, name='store-view'),
    path('<slug>/find/', search_view, name='search-view'),
    path('<slug>/item/<int:item_id>/', product_view, name='item-view'),
    path('<slug>/cart/', cart_view, name='cart-view'),
    path('<slug>/wish/', wish_view, name='wish-view'),
    path('<slug>/checkout/', checkout_view, name='checkout-view'),
    path('<slug>/we-are-closed/', closed_view, name='closed'),

    #+++++++++++++++ URL Methods +++++++++++++++++++

    path('<slug>/cart/item/<int:item_id>/remove/', delete_cart_item, name='delete-cart-item'),
    path('<slug>/cart/item/<int:item_id>/change/', change_cart_item, name='change-cart-quantity'),
    path('<slug>/cart/item/<int:item_id>/add/', increase_cart_item, name='plus'),
    path('<slug>/cart/item/<int:item_id>/minus/', decrease_cart_item, name='minus'),
    path('<slug>/checkout/<invoice_num>/coupon/redeem/', redeem_coupon, name='redeem-coupon'),
    path('<slug>/item/<int:item_id>/add-to-cart/', add_to_cart, name='add-to-cart'),
    path('<slug>/item/<int:item_id>/add-to-wish/', add_to_wish, name='add-to-wish'),
    path('<slug>/wish/<int:item_id>/remove/', remove_wish, name='remove-wish'),
    path('<slug>/checkout/complete/<invoice_num>/', checkout, name='pay'),
    path('<slug>/checkout/success/<int:invoice_num>/', on_checkout_success, name='checkout-complete'),
]

src/vendora/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', include('intro.urls', namespace='base')),
    path('api/', include('api.urls', namespace='api')),
    path('<slug>/admin/', include('vendor.urls', namespace='vendor')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('store/', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/store/views.py
import os
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from datetime import datetime
from django.conf import settings
from django.views.generic import ListView, DetailView
from gateways.payment import vougePay
from store.models import (
    Store, Product,
    Cart, CartItem,
    Invoice, PaymentMethod,
    Coupon, WishList,
    WishItem, 
)
from django.contrib import messages
from random import randint
from django.core.paginator import Paginator
from accounts.models import User
from django.dispatch import Signal





BASE_DIR = settings.BASE_DIR
# User = settings.AUTH_USER_MODEL


#::::::::::::::::::::: Globals :::::::::::::::::::::::::::::::::::

# retieves user's cart
def  getCart(request, slug):
    store = Store.objects.get(slug=slug)
    if not request.user.is_authenticated:
        sessionid = request.session._get_session_key()
        user = User(userslug=sessionid)
        user.set_unusable_password()
        user.save()
        login(request, user)
    try:    # if a user is logged into a store, get his/her cart
        cart = Cart.objects.filter(store=store).get(owner=request.user)
        return cart
    except: # user does not have a cart in this store
        cart = Cart(owner=request.user, store=store)
        cart.save()
        return cart




# retrieves user's wishlist
def getWish(request, slug):
    store = Store.objects.get(slug=slug)
    if not request.user.is_authenticated:
        sessionid = request.session._get_session_key()
        user = User(userslug=sessionid)
        user.set_unusable_password()
        user.save()
        login(request, user)
    try:    # if a user is logged into a store, get his/her cart
        wish = WishList.objects.filter(store=store).get(owner=request.user)
        return wish
    except: # user does not have a cart in this store
        wish = WishList(owner=request.user, store=store)
        wish.save()
        return wish


# Generates an Invoice when the chekout view loads
def makeInvoice(request, cart:Cart, store:Store):
    done = True
    num = ''
    # expired = Invoice.objects.filter(issuer=Store.id).filter(status='pending')
    # print("OLD INVOICES : ", expired)
    # for i in expired.all():
    #     i.delete()
    invoice = Invoice(amount=cart.total(), issuer=store, cart=cart, payer=request.user)
    while done:
        for i in range(0, 11):
            num += str(randint(0, 9))
        try:    # check if an invoice with this number exists
            if not Invoice.objects.get(number=num):
                invoice.number = int(num)
                invoice.save()
                done = False
                break
        except: # invoice does not exist
            invoice.number = int(num)
            invoice.save()
            done = False
            break
    return invoice


#++++++++++++++++++++++ Auth Views ++++++++++++++++++++++++++++++++

# Closed View [redirect to this view only when store's closed]

def closed_view(request, slug):
    store = Store.objects.get(slug=slug)
    if not store.is_open:   # show this page else go to store
        template = '%s/closed.html' % store.template_dir
        context = {
            'store': store,
        }
        return render(request, template, context)
        
    return redirect('store:store-view', slug)

#+++++++++++++++++++++++ Store Views ++++++++++++++++++++++++++++++

# Store View
def store_view(request, slug):
    store = Store.objects.get(slug=slug)
    if not store.is_open:
        return redirect('store:closed', slug)
    cart = getCart(request, slug)
    wish = getWish(request, slug)
    products = store.products.all().order_by('-id')
    template = '%s/home-page.html' % store.template_dir
    pages = Paginator(products, 100, 0)
    page = request.GET.get('page')
    items = pages.get_page(page)
    test = range(0, 8)
    if not store.owner == request.user:
        if request.user in store.customers.all():
            has_account = True
        has_account = False
    else:
        has_account = True
    context = {
        'title': 'Home',
        'items': items,
        'pages': pages,
        'store': store,
        'template': template,
        'test': test,
        'cart': cart,
        'wish': wish,
        'has_account': has_account,
    }
    return render(request, template, context)


# Cart View
def cart_view(request, slug, *args, **kwargs):
    user = request.user
    store = Store.objects.get(slug=slug)
    if not store.is_open:
        return redirect('store:closed', slug)
    cart = getCart(request, slug)
    wish = getWish(request, slug)
    items = cart.items.all().order_by('-id')
    template = '%s/cart.html' % store.template_dir
    context = {
        'title': 'Cart',
        'items': items,
        'store': store,
        'cart': cart,
        'wish': wish,
        'template': template,
    }
    return render(request, template, context)


# WishList View
def wish_view(request, slug, *args, **kwargs):
    user = request.user
    store = Store.objects.get(slug=slug)
    if not store.is_open:
        return redirect('store:closed', slug)
    wish = getWish(request, slug)
    cart = getCart(request, slug)
    items = wish.items.all()
    template = '%s/wish.html' % store.template_dir
    context = {
        'title': 'Wishlist',
        'items': items,
        'store': store,
        'wish': wish,
        'cart': cart,
        'template': template,
    }
    return render(request, template, context)


# Item Detail View
def product_view(request, slug, item_id, *args, **kwargs):
    store = Store.objects.get(slug=slug)
    if not store.is_open:
        return redirect('store:closed', slug)
    products = store.products.all()
    item = Product.objects.get(id=item_id)
    other_items = products.filter(category=item.category)
    template = '%s/product-page.html' % store.template_dir
    cart = getCart(request, slug)
    wish = getWish(request, slug)

    context = {
        'title': 'Product',
        'template': template,
        'item': item,
        'store': store,
        'other_items': other_items[:6],
        'cart': cart,
        'wish': wish,
    }
    return render(request, template, context)
def search_view(request, slug):
    store = Store.objects.get(slug=slug)
    if not store.is_open:
        return redirect('store:closed', slug)
    query = request.POST['query']
    items = []
    name_match = store.products.all().filter(name__contains=query)
    description_match = store.products.all().filter(description__contains=query)
    for i in name_match.all():
        items.append(i)
    for j in description_match.all():
        if not j in items:
            items.append(j)
    cart = getCart(request, store.slug)
    wish = getWish(request, store.slug)
    template = '%s/search-results.html' % store.template_dir
    context = {
        'title': 'Search Results',
        'template': template,
        'query': query,
        'items': items,
        'store': store,
        'cart': cart,
        'wish': wish,
    }
    return render(request, template, context)



# The checkout View
def checkout_view(request, slug):
    user = request.user
    store = Store.objects.get(slug=slug)
    if not store.is_open:
        return redirect('store:closed', slug)
    products = store.products.all()
    cart = getCart(request, store.slug)
    wish = getWish(request, store.slug)
    items = cart.items.all()
    # Generate an Invoice if this is the first time the page loads (redirects inclusive)
    invoice = makeInvoice(request, cart, store)
    if products.count() > 0:
        template = '%s/checkout-page.html' % store.template_dir
    else:
        template = '%s/test-checkout-page.html' % store.template_dir
    context = {
	'title': 'Checkout',
        'store': store,
        'cart': items,
        'wish': wish,
        'order': cart,
        'template': template,
        'invoice': invoice,
    }
    if request.method == "POST":
        gate = vougePay.Order(invoice, store.owner.merchant_id, store)
        data = request.POST        
        card = {
            'phone' : data['card_num'],
            'email' : data['card_num'],
            'card_num' : data['card_num'],
            'card_name' : data['card_name'],
            'card_exp' : data['card_exp'],
            'card_cvv' : data['card_cvv'],
        }

        ship_to = {
            'name' : data['card_num'],
            'address1' : data['address1'],
            'address2' : data['address2'],
            'country' : data['country'],
            'state' : data['state'],
        }

        return checkout(request, slug, invoice.number, gate, card, invoice.amount)

    return render(request, template, context)
    

#+++++++++++++++++++++++++ URL METHODS +++++++++++++++++++++++++++++

# checkout payment processor. This is not the checkout view!
# reacts to payment method specified during checkout.
def checkout(request, slug, invoice_num, gate, card, amt):
    "charge card -> process payment ? successful { payMerchant -> redirect shopper } : { fail -> go back }"
    res = gate.pay(card, amt)
    if res[1] == 'OK':
        messages.success(request, "Checkout Successful! Your order is being processed.")
        return redirect('store:checkout-complete', slug, invoice_num)
    else:
        messages.error(request, "Sorry, The process failed. Try Again")
        return redirect('store:checkout')


# adds an item to cart. default qty = 1
def add_to_cart(request, slug, item_id, *args, **kwargs):
    try:
        quantity = int(request.POST['quantity'])
    except:
        quantity = 1
    product = Product.objects.get(id=item_id)
    store = Store.objects.get(slug=slug)
    cart = getCart(request, slug)
    if quantity < product.quantity:
        item = CartItem(cart=cart ,item=product, quantity=quantity)
        item.save(); cart.items.add(item); cart.save()
        product.quantity -= item.quantity
        product.save()
    return redirect('store:store-view', store.slug)

src/templates/store/default/base.html
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{{store.name}} | {{title}} </title>
  <link href="{% static 'css/store/default/bootstrap/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'css/store/default/mdb/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/store/default/mdb/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/global/scrollbar.css' %}" rel="stylesheet">
  <link href="{% static 'css/store/default/mine/styles.css' %}" rel="stylesheet">
  {% block extra_head %}
  {% endblock extra_head %}
  <link href="/uploads{{store.custom_css}}" rel="Stylesheet">


  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

<body>

{% if messages %}
{% for msg in messages %}
<div class="absolute-center z-depth-5 d-flex">
 <p> {{msg}} </p> 
 <button class="close absolute top-right">&times;</button>
</div>
{% endfor %}
{% endif %}

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'store:store-view' store.slug %}">
        <strong class="blue-text">{{ store.name }}</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'store:store-view' store.slug %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <!-- /Left-->

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons mt-sm-2">
          {% if user.has_usable_password %}
          {% else %}
            <li class="nav-item mr-3 amber">
            <a href="{% url 'accounts:store-signup' store.slug %}" class="nav-link waves-effect white-text">
              <span class="clearfix d-sm-inline-block"> Sign up </span>
            </a>
          </li>
            <li class="nav-item mr-3 blue-grey">
            <a href="{% url 'accounts:store-login' store.slug %}" class="nav-link waves-effect white-text">
              <span class="clearfix d-sm-inline-block"> Login </span>
            </a>
          </li>
          {% endif %}
          
          <li class="nav-item mr-3">
            <a class="nav-link waves-effect cart" 
              {% if store.has_products %}
                href="{% url 'store:cart-view' store.slug %}"
              {% endif %}>
              <span class="badge red badge-pill z-depth-1 mr-1 count">
                {{ cart.count }}
              </span>
              <i class="fas fa-shopping-cart">
                <svg width="1.3em" height="1.3em" viewBox="0 0 16 16" class="blue-text bi bi-cart4" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                </svg>
              </i>
            </a>
          </li>

          <li class="nav-item ml-3">
            <a class="nav-link waves-effect wish" 
              {% if store.has_products %}
                href="{% url 'store:wish-view' store.slug %}"
              {% endif %}>
              <span class="badge red badge-pill z-depth-1 mr-1 count">
                {{ wish.count }}
              </span>
              <i class="">
                <svg width="1.3em" height="1.3em" viewBox="0 0 16 16" class="blue-text bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>
              </i>
            </a>
          </li>

          {% if store.platforms.all > 0 %}
            {% for platform in store.platforms.all %}
              <li class="nav-item">
                <a href="{{ platform.link }}" class="nav-link waves-effect" target="_blank">
                  <i class="fab fa-{{ platform.type|lower }}-f"></i>
                </a>
              </li>
            {% endfor %}
          {% endif %}
        </ul>
        <!-- /Right -->
      </div>
      <!-- /Links -->
    </div>

  </nav>
  <!-- Navbar -->

{% block content %}

{% endblock content %}


  <!--Footer-->
  <footer id="page-footer" class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    {% if store.platforms %}
      <div class="pt-4">
        {% for platform in store.platforms.all%}
          <a class="btn btn-outline-white" href="{{ platform.link }}" target="_blank" role="button">
            <i class="fas fa-download ml-2">{{ platform.type }}</i>
          </a>
        {% endfor %}
      </div>
      <!--/.Call to action-->

    {% endif %}

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="{% url 'store:store-view' store.slug %}" target="_blank"> {{store.name}}.vendora.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/mdb/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb/mdb.js' %}"></script>
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
    let msg = document.querySelector('.msg')

    function hideMsg(){
      msg.style.display = 'none';
    }
  </script>

    
   {% block foot_script %}
   {% endblock foot_script %}

</body>

</html>

src/templates/store/default/cart.html
 {% extends 'default/base.html' %}
 {% load static %} 

{% block content %}

    <style>

        #form1 {
            display: inline-flex;
        }
        .btn-group .btn-blue{
            margin-right: 0;
        }
        #cart-container {
            margin-top: 7em;
        }
        
        table {
            margin: 0 10px;
            margin-top: 7em;
            border-radius: 5px;
        }

        #qty input{
            box-sizing: content-box;
            height: 1.5em;
            border-style: groove;
        }
        
        #qty .btn {
            /* width: fit-content; */
            padding: .2em .7em;
        }
        
        #qty input {
            width: 4em;
        }

        #form-qty {
            text-align: center;
        }
        #control-wrapper .btn {
            padding: 0;
            padding: .2em;
            box-shadow: none;
            margin-top: 0;
            height: 2.3em;
            width: 2em;
        }
        #control-wrapper .btn-danger {
            margin-left: .02rem;
        }

        @media (max-width: 620px){
            table{
                display: block;
            }
        }

        /* .page-footer{
            position: absolute;
            width: 100%;
        }
        */
        @media (max-width: 504px){
            #cart li:not(:last-child){
                display: block !important;
            }
            #item-wrapper{
                justify-content: inherit;
            }
        }
    </style>

    <div class="mt-7 container text-center">
        <div class="text-left">
            <div id="cart" class=" order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill"> {{ cart.count }} </span>
                </h4>
                <ul class="list-group mb-3 items">
                    {% for item in items %}
                    <li id="item" class="list-group-item d-flex justify-content-between item lh-condensed">
                        <div id="item-wrapper" class="d-flex">
                            <div>
                                <h6 class="my-0"> {{ item.item.name }} </h6>
                                <small class="text-muted">{{ item.item.description }}</small>
                            </div>
                            <span class="text-muted pl-1 pr-1">{{ store.currency.symbol }} 
                            {% if item.item.discount_price %}
                                {{ item.item.discount_price }}
                            {% else %}
                                {{ item.item.price }}
                            {% endif %}
                            </span>
                        </div>

                        <div id="control-wrapper">
                            <div class="btn-group">
                                <a class="btn btn-blue " href="{% url 'store:minus' store.slug item.id %}"> - </a>
                                <form method="POST" id="qty" action="{% url 'store:change-cart-quantity' store.slug item.id %}">
                                    {% csrf_token %}
                                    <input type="number" id="form-qty" name="quantity" value={{item.quantity}} title="
                                Hit enter when done.
                                ">
                                </form>
                                <a class="btn btn-danger" href="{% url 'store:plus' store.slug item.id %}"> + </a>
                                <a class="btn btn-dark" href="{% url 'store:delete-cart-item' store.slug item.id %}"> &times; </a>
                            </div>
                        </div>
                    </li>
                    {% endfor %}

                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total ({{ store.currency.code }})</span>
                        <strong>{{ store.currency.symbol }}{{cart.total}}</strong>
                    </li>
                </ul>

            </div>
        </div>

        <a id="checkout" href="{% url 'store:store-view' store.slug %}" class="btn bg-primary text-white">
            Continue Shopping
        </a>

        <a id="checkout" 
        {% if cart.count > 0 %}
	        href="{% url 'store:checkout-view' store.slug %}" 
	{% endif %}
        class="btn btn-cyan">
            Proceed to ckeckout
        </a>
    </div>

{% endblock content %}

  {% block foot_script %}
<script>
    let footer = document.querySelector('.page-footer')
    let items = document.querySelector('.items')
    if(items.scrollHeight < 300){
        footer.style.position = 'fixed'
        footer.style.bottom = '0;'
        footer.style.width = '100%'
        console.log("Footer is", footer)
        console.log("ITEMS", items)

    }
</script>
  {% endblock foot_script %}

src/templates/store/default/closed.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{store.name}} | We're Closed</title>
    <style>
        #info-box {
            width: 90vw;
            margin: auto;
            text-align: center;
            margin-top: 20vh;
            background: salmon;
            color: floralwhite;
            padding: 3em .5em;
            font-size: larger;
        }
    </style>
</head>

<body>
    <div id="info-box" class="m-auto absolute-center">
        <h3> Sorry we're closed for the day. </h3>
        <h6> But you can check back at our opening hours : {{opening_hours}} </h6>
        <h4 id="countdown"></h4>
    </div>
</body>
</html>